### PR TITLE
Fix re add dataset bug

### PR DESCRIPTION
**Pull request by akatuluru**

### CODE REVIEW

**Comment by akatuluru** [comment]
this patch fixes the clean up code to drop the orphaned view when the table_quota goes over the limit while importing the datalib dataset

**Comment by mbektas** [comment]
looks good to me

**Comment by akatuluru** [comment]
as suggested by https://github.com/CartoDB/cartodb-bloomberg/issues/197

**Comment by vmanohar1** [comment]
Reviewing..

**Pull request merged**
