### PR TITLE
Support bulk user deletion for testing purposes

### PR DESCRIPTION
**Pull request by tylerparsons**
* Enable turning off interactive prompt in user deletion rake task with `:force` flag
* Add script to to bulk delete users provided in file

### CODE REVIEW

**Comment by mbektash** [comment]
@tylerparsons @vmanohar1 what is the status of this? do you still want this merged?

**Comment by vmanohar1** [comment]
Don't merge since it is not yet reviewed..

**Comment by tylerparsons** [comment]
We noticed some failed user deletions when using this script in QA - further investigation is needed before determining the cause.

If it is something we think will be useful in the future, I can investigate further, otherwise we can close this PR.

**Comment by mbektash** [comment]
Closing for now. We can revisit after backend merge with carto.

**Pull request closed without merging**
